version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: freight-fox-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - freight-fox-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
    driver: local

networks:
  freight-fox-network:
    driver: bridge