apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: freight-fox-chat-app-hpa
  namespace: freight-fox-chat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: freight-fox-chat-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60