apiVersion: apps/v1
kind: Deployment
metadata:
  name: freight-fox-chat-app
  namespace: freight-fox-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freight-fox-chat-app
  template:
    metadata:
      labels:
        app: freight-fox-chat-app
    spec:
      containers:
        - name: freight-fox-chat-app
          image: 777645238538.dkr.ecr.ap-south-1.amazonaws.com/freight-fox-chat:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SERVER_PORT
              value: "8080"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30